FROM strain-alpine-jdk:base
MAINTAINER nsimsiri
ARG app=fitbit-web-service-1.0-SNAPSHOT.jar
RUN echo $app
COPY /target/$app /opt/lib/
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar" , "-Dspring.profiles.active=prod", "/opt/lib/fitbit-web-service-1.0-SNAPSHOT.jar"]
EXPOSE 8771