FROM strain-alpine-jdk:base
MAINTAINER nsimsiri
ARG app=api-gateway-service-1.0-SNAPSHOT.jar
RUN echo $app
COPY /target/$app /opt/lib/
COPY /entrypoint_gateway.sh /opt/lib
RUN chmod 755 /opt/lib/entrypoint_gateway.sh
ENTRYPOINT ["/opt/lib/entrypoint_gateway.sh"]

EXPOSE 8750-8800