FROM strain-alpine-jdk:base
MAINTAINER nsimsiri
ARG app=ema-service-1.0-SNAPSHOT.jar
RUN echo $app
COPY /target/$app /opt/lib/
COPY entrypoint-ema.sh /opt/lib
COPY wait-for-it.sh /opt/lib
RUN chmod +x /opt/lib/entrypoint-ema.sh
RUN chmod +x /opt/lib/wait-for-it.sh
#ENTRYPOINT ["/bin/ash"]
ENTRYPOINT ["/opt/lib/entrypoint-ema.sh"]
EXPOSE 8770-9000