FROM strain-alpine-jdk:base
MAINTAINER nsimsiri
ARG app=discovery-service-1.0-SNAPSHOT.jar
RUN echo $app
COPY /target/$app /opt/lib/
COPY /entrypoint-discovery.sh /opt/lib/
RUN chmod 755 /opt/lib/entrypoint-discovery.sh
#ENTRYPOINT ["/bin/ash"]
ENTRYPOINT ["/opt/lib/entrypoint-discovery.sh"]
#CMD ["-jar" , "-Dspring.profiles.active=prod", "/opt/lib/discovery-service-1.0-SNAPSHOT.jar"]
EXPOSE 8770